name: Cyrafa CRM Workflow

on:
  push:
    branches:
      - client/cyrafa #

jobs:
  deploy:
    environment: CYRAFA
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/client/cyrafa' # we tell Github to only execute this step if we're on our master branch (so we don't put unfinished branches in production)
    steps:
      - name: Deploying to CRM Server
        env: 
          CYRAFA_CRM_PATH: ${{ secrets.CYRAFA_CRM_PATH }}
          CYRAFA_BRANCH_NAME: ${{ secrets.CYRAFA_BRANCH_NAME }}
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.CYRAFA_HOST }}
          username: ${{ secrets.CYRAFA_USERNAME }}
          password: ${{ secrets.CYRAFA_PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: 
            CYRAFA_CRM_PATH,CYRAFA_BRANCH_NAME
          script: |
            echo "$CYRAFA_CRM_PATH"
            cd "$CYRAFA_CRM_PATH" # we move into our app's folder
            git checkout "$CYRAFA_BRANCH_NAME"
            git pull origin "$CYRAFA_BRANCH_NAME" # we pull any changes from git
            npm prune --legacy-peer-deps # we remove any unused dependencies
            npm install --legacy-peer-deps # we install any missing dependencies
            npm run buildVm 
