// fetch forex BOUNSES
export const FETCH_FOREX_BOUNSES_REQUESTED = "FETCH_FOREX_BOUNSES_REQUESTED";
export const FETCH_FOREX_BOUNSES_SUCCESS = "FETCH_FOREX_BOUNSES_SUCCESS";
export const FETCH_FOREX_BOUNSES_FAIL = "FETCH_FOREX_BOUNSES_FAIL";

export const ADD_FOREX_BOUNSE_REQUESTED = "ADD_FOREX_BOUNSE_REQUESTED";
export const ADD_FOREX_BOUNSE_SUCCESS = "ADD_FOREX_BOUNSE_SUCCESS";
export const ADD_FOREX_BOUNSE_FAIL = "ADD_FOREX_BOUNSE_FAIL";
export const ADD_FOREX_BOUNSE_CLEAR = "ADD_FOREX_BOUNSE_CLEAR";
export const ADD_FOREX_BOUNSE_ERROR_CLEAR = "ADD_FOREX_BOUNSE_ERROR_CLEAR";
export const APPROVE_FOREX_BOUNSE = "APPROVE_FOREX_BOUNSE";
export const APPROVE_FOREX_BOUNSE_SUCCESS = "APPROVE_FOREX_BOUNSE_SUCCESS";
export const REJECT_FOREX_BOUNSE = "REJECT_FOREX_BOUNSE";
export const REJECT_FOREX_BOUNSE_SUCCESS = "REJECT_FOREX_BOUNSE_SUCCESS";