export const EDIT_PROFILE = "EDIT_PROFILE";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const RESET_PROFILE_FLAG = "RESET_PROFILE_FLAG";
export const FETCH_PROFILE_START = "FETCH_PROFILE_START";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";

export const SUBMIT_IND_PROFILE_START = "SUBMIT_IND_PROFILE_START";
export const SUBMIT_IND_PROFILE_END = "SUBMIT_IND_PROFILE_END";

export const CONVERT_PROFILE_REQUESTED = "CONVERT_PROFILE_REQUESTED";
export const CONVERT_PROFILE_SUCCESS = "CONVERT_PROFILE_SUCCESS";
export const CONVERT_PROFILE_FAIL = "CONVERT_PROFILE_FAIL";